package de.abg.jreichert.activeanno.jpa;

import org.eclipse.xtend.core.compiler.batch.XtendCompilerTester;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.xbase.lib.Extension;
import org.junit.Test;

@SuppressWarnings("all")
public class EntityLiteralTest {
  @Extension
  private XtendCompilerTester compilerTester /* Skipped initializer because of errors */;
  
  @Test
  public void testEntityLiteral() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("@de.abg.jreichert.activeanno.jpa.EntityLiteral");
    _builder.newLine();
    _builder.append("class MyClass {");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("String fieldWithoutAnnotation;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@de.abg.jreichert.activeanno.jpa.Property");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("String fieldWithAnnotation;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@de.abg.jreichert.activeanno.jpa.Property");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("MyClass2 fieldWithAnnotationAndEntityType;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("@de.abg.jreichert.activeanno.jpa.EntityLiteral");
    _builder.newLine();
    _builder.append("class MyClass2 {");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("String fieldWithoutAnnotation;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@de.abg.jreichert.activeanno.jpa.Property");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("String fieldWithAnnotation;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("class MyClass3 {");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("String fieldWithoutAnnotation;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@de.abg.jreichert.activeanno.jpa.Property");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("String fieldWithAnnotation;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("MULTIPLE FILES WERE GENERATED");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("File 1 : MyClass.java");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("import de.abg.jreichert.activeanno.jpa.EntityLiteral;");
    _builder_1.newLine();
    _builder_1.append("import de.abg.jreichert.activeanno.jpa.Property;");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("@EntityLiteral");
    _builder_1.newLine();
    _builder_1.append("@SuppressWarnings(\"all\")");
    _builder_1.newLine();
    _builder_1.append("public class MyClass {");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("private String fieldWithoutAnnotation;");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("@Property");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("private String fieldWithAnnotation;");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("@Property");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("private MyClass2 fieldWithAnnotationAndEntityType;");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("public String getFieldWithAnnotation() {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("return this.fieldWithAnnotation;");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("public void setFieldWithAnnotation(final String fieldWithAnnotation) {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("this.fieldWithAnnotation = fieldWithAnnotation;");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("public MyClass2 getFieldWithAnnotationAndEntityType() {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("return this.fieldWithAnnotationAndEntityType;");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("public void setFieldWithAnnotationAndEntityType(final MyClass2 fieldWithAnnotationAndEntityType) {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("this.fieldWithAnnotationAndEntityType = fieldWithAnnotationAndEntityType;");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("File 2 : MyClass2.java");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("import de.abg.jreichert.activeanno.jpa.EntityLiteral;");
    _builder_1.newLine();
    _builder_1.append("import de.abg.jreichert.activeanno.jpa.Property;");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("@EntityLiteral");
    _builder_1.newLine();
    _builder_1.append("@SuppressWarnings(\"all\")");
    _builder_1.newLine();
    _builder_1.append("public class MyClass2 {");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("private String fieldWithoutAnnotation;");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("@Property");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("private String fieldWithAnnotation;");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("public String getFieldWithAnnotation() {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("return this.fieldWithAnnotation;");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("public void setFieldWithAnnotation(final String fieldWithAnnotation) {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("this.fieldWithAnnotation = fieldWithAnnotation;");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("File 3 : MyClass2Literal.java");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("import org.sculptor.framework.domain.Property;");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("@SuppressWarnings(\"all\")");
    _builder_1.newLine();
    _builder_1.append("public class MyClass2Literal<T> extends MyClass2LiteralImpl<T> implements Property<T> {");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("private final static long serialVersionUID = 1L;");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("public MyClass2Literal(final String parentPath, final String additionalPath, final Class<T> owningClass) {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("super(parentPath, additionalPath, owningClass);");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("File 4 : MyClass2LiteralImpl.java");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("import org.sculptor.framework.domain.LeafProperty;");
    _builder_1.newLine();
    _builder_1.append("import org.sculptor.framework.domain.PropertiesCollection;");
    _builder_1.newLine();
    _builder_1.append("import org.sculptor.framework.domain.Property;");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("@SuppressWarnings(\"all\")");
    _builder_1.newLine();
    _builder_1.append("public class MyClass2LiteralImpl<T> extends PropertiesCollection {");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("private final static long serialVersionUID = 1L;");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("private Class<T> owningClass;");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("public MyClass2LiteralImpl(final Class<T> owningClass) {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("super(null);");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("this.owningClass = owningClass;");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("public MyClass2LiteralImpl(final String parentPath, final String additionalPath, final Class<T> owningClass) {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("super(parentPath, additionalPath);");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("this.owningClass = owningClass;");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("public Property<T> fieldWithAnnotation() {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("return new LeafProperty<T>(getParentPath(), \"fieldWithAnnotation\", false, owningClass);");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("File 5 : MyClass2Literals.java");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("import org.sculptor.framework.domain.Property;");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("@SuppressWarnings(\"all\")");
    _builder_1.newLine();
    _builder_1.append("public class MyClass2Literals {");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("private final static MyClass2LiteralImpl<MyClass2> sharedInstance = new MyClass2LiteralImpl<MyClass2>(MyClass2.class);;");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("private MyClass2Literals() {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("public static Property<MyClass2> fieldWithAnnotation() {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("return sharedInstance.fieldWithAnnotation();");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("File 6 : MyClass3.java");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("import de.abg.jreichert.activeanno.jpa.Property;");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("@SuppressWarnings(\"all\")");
    _builder_1.newLine();
    _builder_1.append("public class MyClass3 {");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("private String fieldWithoutAnnotation;");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("@Property");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("private String fieldWithAnnotation;");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("public String getFieldWithAnnotation() {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("return this.fieldWithAnnotation;");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("public void setFieldWithAnnotation(final String fieldWithAnnotation) {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("this.fieldWithAnnotation = fieldWithAnnotation;");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("File 7 : MyClassLiteral.java");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("import org.sculptor.framework.domain.Property;");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("@SuppressWarnings(\"all\")");
    _builder_1.newLine();
    _builder_1.append("public class MyClassLiteral<T> extends MyClassLiteralImpl<T> implements Property<T> {");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("private final static long serialVersionUID = 1L;");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("public MyClassLiteral(final String parentPath, final String additionalPath, final Class<T> owningClass) {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("super(parentPath, additionalPath, owningClass);");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("File 8 : MyClassLiteralImpl.java");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("import org.sculptor.framework.domain.LeafProperty;");
    _builder_1.newLine();
    _builder_1.append("import org.sculptor.framework.domain.PropertiesCollection;");
    _builder_1.newLine();
    _builder_1.append("import org.sculptor.framework.domain.Property;");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("@SuppressWarnings(\"all\")");
    _builder_1.newLine();
    _builder_1.append("public class MyClassLiteralImpl<T> extends PropertiesCollection {");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("private final static long serialVersionUID = 1L;");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("private Class<T> owningClass;");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("public MyClassLiteralImpl(final Class<T> owningClass) {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("super(null);");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("this.owningClass = owningClass;");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("public MyClassLiteralImpl(final String parentPath, final String additionalPath, final Class<T> owningClass) {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("super(parentPath, additionalPath);");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("this.owningClass = owningClass;");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("public Property<T> fieldWithAnnotation() {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("return new LeafProperty<T>(getParentPath(), \"fieldWithAnnotation\", false, owningClass);");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("public MyClass2Literal<T> fieldWithAnnotationAndEntityType() {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("return new MyClass2Literal<T>(getParentPath(), \"fieldWithAnnotationAndEntityType\", owningClass);");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("File 9 : MyClassLiterals.java");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("import org.sculptor.framework.domain.Property;");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("@SuppressWarnings(\"all\")");
    _builder_1.newLine();
    _builder_1.append("public class MyClassLiterals {");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("private final static MyClassLiteralImpl<MyClass> sharedInstance = new MyClassLiteralImpl<MyClass>(MyClass.class);;");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("private MyClassLiterals() {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("public static Property<MyClass> fieldWithAnnotation() {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("return sharedInstance.fieldWithAnnotation();");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("public static MyClass2Literal<MyClass> fieldWithAnnotationAndEntityType() {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("return sharedInstance.fieldWithAnnotationAndEntityType();");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.newLine();
    this.compilerTester.assertCompilesTo(_builder, _builder_1);
  }
}
